### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by kolako54** [frontendmonster/vscode-skill-theme#1]
I found some weird bug in your awesome theme, please fix these notes as soon as possible. it's real pity for who likes your theme!
Regards.
![Screenshot (343)](https://user-images.githubusercontent.com/50197765/71311601-4eac4200-2435-11ea-8386-7a912bb5160a.png)

**Comment by ASafaeirad** [comment]
Punctuation color is "#FFB68E" in skill-theme, so the problem source should be from another extension.
Btw, thanks for your feedback.
I'll close the issue.
